package thedmitr.survivors.common.blocks;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import thedmitr.survivors.Survivors;
import thedmitr.survivors.common.ItemTabs;
import thedmitr.survivors.common.blocks.rail.RailAngleBlock;
import thedmitr.survivors.common.blocks.rail.RailLineBlock;

import java.util.HashMap;
import java.util.Map;

public class SurvivorsBlocks {

    private static final Map<String, Block> blocks_map = new HashMap<>();

    public static Block get(String name) {
        name = "tile." + name;
        if (!blocks_map.containsKey(name))
            return null;
        return blocks_map.get(name);
    }

    private static void register(Block block) {
        block.setCreativeTab(ItemTabs.blocks_tab);
        GameRegistry.registerBlock(block, block.getUnlocalizedName());
        blocks_map.put(block.getUnlocalizedName(), block);
    }

    public static void register() {
        register(new GeneralBlock("survivors_block_7", Survivors.MODID + ":metal/" + "metal_1"));
        register(new GeneralBlock("survivors_block_8", Survivors.MODID + ":metal/" + "metal_2"));
        register(new GeneralBlock("survivors_block_9", Survivors.MODID + ":metal/" + "metal_3"));
        register(new GeneralBlock("survivors_block_10", Survivors.MODID + ":metal/" + "metal_4"));
        register(new GeneralBlock("survivors_block_11", Survivors.MODID + ":metal/" + "metal_5"));
        register(new GeneralBlock("survivors_block_12", Survivors.MODID + ":metal/" + "metal_6"));
        register(new GeneralBlock("survivors_block_13", Survivors.MODID + ":metal/" + "metal_7"));
        register(new GeneralBlock("survivors_block_14", Survivors.MODID + ":metal/" + "metal_8"));
        register(new GeneralBlock("survivors_block_15", Survivors.MODID + ':' + "gravel"));
        register(new GeneralBlock("survivors_block_16", Survivors.MODID + ':' + "brown_wool"));
        register(new GeneralBlock("survivors_block_18", Survivors.MODID + ':' + "box_1"));
        register(new GeneralTransparentBlock("survivors_block_19", Survivors.MODID + ":metal/" + "metal_9"));
        register(new TimberBlock("survivors_block_20", Survivors.MODID + ':' + "tire_1"));
        register(new TimberBlock("survivors_block_21", Survivors.MODID + ':' + "barrel_1"));
        register(new BushBlock("survivors_block_23", Survivors.MODID + ":bush/" + "bush_1"));
        register(new BushBlock("survivors_block_24", Survivors.MODID + ":bush/" + "bush_2"));
        register(new BushBlock("survivors_block_25", Survivors.MODID + ":bush/" + "bush_3"));
        register(new BushBlock("survivors_block_26", Survivors.MODID + ":bush/" + "bush_4"));
        register(new BushBlock("survivors_block_27", Survivors.MODID + ":bush/" + "bush_5"));
        register(new BushBlock("survivors_block_28", Survivors.MODID + ":bush/" + "bush_6"));
        register(new BushBlock("survivors_block_29", Survivors.MODID + ":bush/" + "bush_7"));
        register(new BushBlock("survivors_block_30", Survivors.MODID + ":bush/" + "bush_8"));
        register(new BushBlock("survivors_block_31", Survivors.MODID + ":bush/" + "bush_9"));
        register(new BushBlock("survivors_block_32", Survivors.MODID + ":bush/" + "bush_10"));
        register(new BushBlock("survivors_block_33", Survivors.MODID + ":bush/" + "bush_11"));
        register(new BushBlock("survivors_block_34", Survivors.MODID + ":bush/" + "bush_12"));
        register(new BushBlock("survivors_block_35", Survivors.MODID + ":bush/" + "bush_13"));
        register(new BushBlock("survivors_block_36", Survivors.MODID + ":bush/" + "bush_14"));
        register(new BushBlock("survivors_block_37", Survivors.MODID + ":bush/" + "bush_15"));
        register(new BushBlock("survivors_block_38", Survivors.MODID + ":bush/" + "bush_16"));
        register(new BushBlock("survivors_block_39", Survivors.MODID + ":bush/" + "bush_17"));
        register(new RailLineBlock("survivors_block_43", Survivors.MODID + ':' + "rail/gravel_rail", Survivors.MODID + ':' + "gravel"));
        register(new RailAngleBlock("survivors_block_44", Survivors.MODID + ':' + "rail/gravel_rail", Survivors.MODID + ':' + "gravel"));
        register(new TimberBlock("survivors_block_45", Survivors.MODID + ':' + "timber_1"));
        register(new BarbedWireBlock("survivors_block_46", Survivors.MODID + ':' + "barbed_wire_1"));
        register(new BarbedWireBlock("survivors_block_47", Survivors.MODID + ':' + "barbed_wire_2"));
        register(new GeneralBlock("survivors_block_48", Survivors.MODID + ':' + "bricks/bricks_1"));
        register(new GeneralBlock("survivors_block_49", Survivors.MODID + ':' + "bricks/bricks_2"));
        register(new GeneralBlock("survivors_block_50", Survivors.MODID + ':' + "bricks/bricks_3"));
        register(new GeneralBlock("survivors_block_51", Survivors.MODID + ':' + "bricks/bricks_4"));
        register(new GeneralBlock("survivors_block_52", Survivors.MODID + ':' + "bricks/bricks_5"));
        register(new GeneralBlock("survivors_block_53", Survivors.MODID + ':' + "bricks/bricks_6"));
        register(new GeneralBlock("survivors_block_54", Survivors.MODID + ':' + "bricks/bricks_7"));
        register(new GeneralBlock("survivors_block_55", Survivors.MODID + ':' + "bricks/bricks_8"));
        register(new GeneralBlock("survivors_block_56", Survivors.MODID + ':' + "bricks/bricks_9"));
        register(new GeneralBlock("survivors_block_57", Survivors.MODID + ':' + "bricks/bricks_10"));
        register(new GeneralBlock("survivors_block_58", Survivors.MODID + ':' + "bricks/bricks_11"));
        register(new GeneralBlock("survivors_block_59", Survivors.MODID + ':' + "bricks/bricks_12"));
        register(new GeneralBlock("survivors_block_60", Survivors.MODID + ':' + "bricks/bricks_13"));
        register(new GeneralBlock("survivors_block_61", Survivors.MODID + ':' + "bricks/bricks_14"));
        register(new GeneralBlock("survivors_block_62", Survivors.MODID + ':' + "bricks/bricks_15"));
        register(new GeneralBlock("survivors_block_63", Survivors.MODID + ':' + "bricks/bricks_16"));
        register(new GeneralBlock("survivors_block_64", Survivors.MODID + ':' + "bricks/bricks_17"));
        register(new GeneralBlock("survivors_block_65", Survivors.MODID + ':' + "bricks/bricks_18"));
        register(new GeneralBlock("survivors_block_66", Survivors.MODID + ':' + "bricks/bricks_19"));
        register(new GeneralBlock("survivors_block_67", Survivors.MODID + ':' + "bricks/bricks_20"));
        register(new GeneralBlock("survivors_block_68", Survivors.MODID + ':' + "bricks/bricks_21"));
        register(new GeneralBlock("survivors_block_69", Survivors.MODID + ':' + "bricks/bricks_22"));
        register(new GeneralBlock("survivors_block_70", Survivors.MODID + ':' + "bricks/bricks_23"));
        register(new GeneralBlock("survivors_block_71", Survivors.MODID + ':' + "bricks/bricks_24"));
        register(new GeneralBlock("survivors_block_72", Survivors.MODID + ':' + "bricks/bricks_25"));
        register(new GeneralBlock("survivors_block_73", Survivors.MODID + ':' + "bricks/bricks_26"));
        register(new GeneralBlock("survivors_block_74", Survivors.MODID + ':' + "bricks/bricks_27"));
        register(new GeneralBlock("survivors_block_75", Survivors.MODID + ':' + "bricks/bricks_28"));
        register(new GeneralBlock("survivors_block_76", Survivors.MODID + ':' + "bricks/bricks_29"));
        register(new GeneralBlock("survivors_block_77", Survivors.MODID + ':' + "bricks/bricks_30"));
        register(new GeneralBlock("survivors_block_78", Survivors.MODID + ':' + "bricks/bricks_31"));
        register(new GeneralBlock("survivors_block_79", Survivors.MODID + ':' + "bricks/bricks_32"));
        register(new GeneralBlock("survivors_block_80", Survivors.MODID + ':' + "bricks/bricks_33"));
        register(new GeneralBlock("survivors_block_81", Survivors.MODID + ':' + "bricks/bricks_34"));
        register(new GeneralBlock("survivors_block_82", Survivors.MODID + ':' + "bricks/bricks_35"));
        register(new GeneralBlock("survivors_block_83", Survivors.MODID + ':' + "bricks/bricks_36"));
        register(new GeneralBlock("survivors_block_84", Survivors.MODID + ':' + "bricks/bricks_37"));
        register(new GeneralBlock("survivors_block_85", Survivors.MODID + ':' + "parget/parget_1"));
        register(new GeneralBlock("survivors_block_86", Survivors.MODID + ':' + "parget/parget_2"));
        register(new GeneralBlock("survivors_block_87", Survivors.MODID + ':' + "parget/parget_3"));
        register(new GeneralBlock("survivors_block_88", Survivors.MODID + ':' + "parget/parget_4"));
        register(new GeneralBlock("survivors_block_89", Survivors.MODID + ':' + "parget/parget_5"));
        register(new GeneralBlock("survivors_block_90", Survivors.MODID + ':' + "parget/parget_6"));
        register(new GeneralBlock("survivors_block_91", Survivors.MODID + ':' + "parget/parget_7"));
        register(new GeneralBlock("survivors_block_92", Survivors.MODID + ':' + "parget/parget_8"));
        register(new GeneralBlock("survivors_block_93", Survivors.MODID + ':' + "parget/parget_9"));
        register(new GeneralBlock("survivors_block_94", Survivors.MODID + ':' + "parget/parget_10"));
        register(new GeneralBlock("survivors_block_95", Survivors.MODID + ':' + "parget/parget_11"));
        register(new GeneralBlock("survivors_block_96", Survivors.MODID + ':' + "parget/parget_12"));
        register(new GeneralBlock("survivors_block_97", Survivors.MODID + ':' + "planks/planks_1"));
        register(new GeneralBlock("survivors_block_98", Survivors.MODID + ':' + "planks/planks_2"));
        register(new GeneralBlock("survivors_block_99", Survivors.MODID + ':' + "planks/planks_3"));
        register(new GeneralBlock("survivors_block_100", Survivors.MODID + ':' + "planks/planks_4"));
        register(new GeneralBlock("survivors_block_101", Survivors.MODID + ':' + "planks/planks_5"));
        register(new GeneralBlock("survivors_block_102", Survivors.MODID + ':' + "planks/planks_6"));
        register(new GeneralBlock("survivors_block_103", Survivors.MODID + ':' + "planks/planks_7"));
        register(new GeneralBlock("survivors_block_104", Survivors.MODID + ':' + "planks/planks_8"));
        register(new GeneralBlock("survivors_block_105", Survivors.MODID + ':' + "planks/planks_9"));
        register(new GeneralBlock("survivors_block_106", Survivors.MODID + ':' + "planks/planks_10"));
        register(new GeneralBlock("survivors_block_107", Survivors.MODID + ':' + "planks/planks_11"));
        register(new GeneralBlock("survivors_block_108", Survivors.MODID + ':' + "planks/planks_12"));
        register(new GeneralBlock("survivors_block_109", Survivors.MODID + ':' + "planks/planks_13"));
        register(new GeneralBlock("survivors_block_110", Survivors.MODID + ':' + "planks/planks_14"));
        register(new GeneralBlock("survivors_block_111", Survivors.MODID + ':' + "planks/planks_15"));
        register(new GeneralBlock("survivors_block_112", Survivors.MODID + ':' + "planks/planks_16"));
        register(new GeneralBlock("survivors_block_113", Survivors.MODID + ':' + "planks/planks_17"));
        register(new GeneralBlock("survivors_block_114", Survivors.MODID + ':' + "planks/planks_18"));
        register(new GeneralBlock("survivors_block_115", Survivors.MODID + ':' + "planks/planks_19"));
        register(new GeneralBlock("survivors_block_116", Survivors.MODID + ':' + "planks/planks_20"));
        register(new GeneralBlock("survivors_block_117", Survivors.MODID + ':' + "planks/planks_21"));
        register(new GeneralBlock("survivors_block_118", Survivors.MODID + ':' + "planks/planks_22"));
        register(new GeneralBlock("survivors_block_119", Survivors.MODID + ':' + "planks/planks_23"));
        register(new GeneralBlock("survivors_block_120", Survivors.MODID + ':' + "planks/planks_24"));
        register(new GeneralBlock("survivors_block_121", Survivors.MODID + ':' + "planks/planks_25"));
        register(new GeneralBlock("survivors_block_122", Survivors.MODID + ':' + "planks/planks_26"));
        register(new GeneralBlock("survivors_block_123", Survivors.MODID + ':' + "planks/planks_27"));
        register(new GeneralBlock("survivors_block_124", Survivors.MODID + ':' + "planks/planks_28"));
        register(new GeneralBlock("survivors_block_125", Survivors.MODID + ':' + "planks/planks_29"));
        register(new GeneralBlock("survivors_block_126", Survivors.MODID + ':' + "planks/planks_30"));
        register(new GeneralBlock("survivors_block_127", Survivors.MODID + ':' + "planks/planks_31"));
        register(new GeneralBlock("survivors_block_128", Survivors.MODID + ':' + "planks/planks_32"));
        register(new GeneralBlock("survivors_block_129", Survivors.MODID + ':' + "planks/planks_33"));
        register(new GeneralBlock("survivors_block_130", Survivors.MODID + ':' + "planks/planks_34"));
        register(new GeneralBlock("survivors_block_131", Survivors.MODID + ':' + "planks/planks_35"));
        register(new GeneralBlock("survivors_block_132", Survivors.MODID + ':' + "planks/planks_36"));
        register(new GeneralBlock("survivors_block_133", Survivors.MODID + ':' + "planks/planks_37"));
        register(new GeneralBlock("survivors_block_134", Survivors.MODID + ':' + "planks/planks_38"));
        register(new GeneralBlock("survivors_block_135", Survivors.MODID + ':' + "planks/planks_39"));
        register(new GeneralBlock("survivors_block_136", Survivors.MODID + ':' + "planks/planks_40"));
        register(new GeneralBlock("survivors_block_137", Survivors.MODID + ':' + "planks/planks_41"));
        register(new GeneralBlock("survivors_block_138", Survivors.MODID + ':' + "planks/planks_42"));
        register(new GeneralBlock("survivors_block_139", Survivors.MODID + ":metal/" + "metal_10"));
        register(new GeneralBlock("survivors_block_140", Survivors.MODID + ":metal/" + "metal_11"));
        register(new GeneralBlock("survivors_block_141", Survivors.MODID + ":metal/" + "metal_12"));
        register(new GeneralBlock("survivors_block_142", Survivors.MODID + ":metal/" + "metal_13"));
        register(new GeneralBlock("survivors_block_143", Survivors.MODID + ":metal/" + "metal_14"));
        register(new GeneralBlock("survivors_block_144", Survivors.MODID + ":metal/" + "metal_15"));
        register(new GeneralBlock("survivors_block_145", Survivors.MODID + ":metal/" + "metal_16"));
        register(new GeneralBlock("survivors_block_146", Survivors.MODID + ":metal/" + "metal_17"));
        register(new GeneralBlock("survivors_block_147", Survivors.MODID + ":metal/" + "metal_18"));
        register(new GeneralBlock("survivors_block_148", Survivors.MODID + ":metal/" + "metal_19"));
        register(new GeneralBlock("survivors_block_149", Survivors.MODID + ":metal/" + "metal_20"));
        register(new GeneralBlock("survivors_block_150", Survivors.MODID + ":metal/" + "metal_21"));
        register(new GeneralBlock("survivors_block_151", Survivors.MODID + ":metal/" + "metal_22"));
        register(new GeneralBlock("survivors_block_152", Survivors.MODID + ":metal/" + "metal_23"));
        register(new GeneralBlock("survivors_block_153", Survivors.MODID + ":metal/" + "metal_24"));
        register(new GeneralBlock("survivors_block_154", Survivors.MODID + ":metal/" + "metal_25"));
        register(new GeneralBlock("survivors_block_155", Survivors.MODID + ":metal/" + "metal_26"));
        register(new GeneralBlock("survivors_block_156", Survivors.MODID + ":metal/" + "metal_27"));
        register(new GeneralBlock("survivors_block_157", Survivors.MODID + ":metal/" + "metal_28"));
        register(new GeneralBlock("survivors_block_158", Survivors.MODID + ":metal/" + "metal_29"));
        register(new GeneralBlock("survivors_block_159", Survivors.MODID + ":metal/" + "metal_30"));
        register(new GeneralBlock("survivors_block_160", Survivors.MODID + ":metal/" + "metal_31"));
        register(new GeneralBlock("survivors_block_161", Survivors.MODID + ":metal/" + "metal_32"));
        register(new GeneralBlock("survivors_block_162", Survivors.MODID + ":metal/" + "metal_33"));
        register(new GeneralBlock("survivors_block_163", Survivors.MODID + ":metal/" + "metal_34"));
        register(new GeneralBlock("survivors_block_164", Survivors.MODID + ":metal/" + "metal_35"));
        register(new GeneralBlock("survivors_block_165", Survivors.MODID + ":metal/" + "metal_36"));
        register(new GeneralBlock("survivors_block_166", Survivors.MODID + ":metal/" + "metal_37"));
        register(new GeneralBlock("survivors_block_167", Survivors.MODID + ":metal/" + "metal_38"));
        register(new GeneralBlock("survivors_block_168", Survivors.MODID + ":metal/" + "metal_39"));
        register(new GeneralBlock("survivors_block_169", Survivors.MODID + ":metal/" + "metal_40"));
        register(new GeneralBlock("survivors_block_170", Survivors.MODID + ":metal/" + "metal_41"));
        register(new GeneralBlock("survivors_block_171", Survivors.MODID + ":metal/" + "metal_42"));
        register(new GeneralBlock("survivors_block_172", Survivors.MODID + ":metal/" + "metal_43"));
        register(new GeneralBlock("survivors_block_173", Survivors.MODID + ":metal/" + "metal_44"));
        register(new GeneralBlock("survivors_block_174", Survivors.MODID + ":metal/" + "metal_45"));
        register(new GeneralBlock("survivors_block_175", Survivors.MODID + ":metal/" + "metal_46"));
        register(new GeneralBlock("survivors_block_176", Survivors.MODID + ":metal/" + "metal_47"));
        register(new GeneralBlock("survivors_block_177", Survivors.MODID + ":metal/" + "metal_48"));
        register(new GeneralBlock("survivors_block_178", Survivors.MODID + ":metal/" + "metal_49"));
        register(new GeneralBlock("survivors_block_179", Survivors.MODID + ":metal/" + "metal_50"));
        register(new GeneralBlock("survivors_block_180", Survivors.MODID + ":metal/" + "metal_51"));
        register(new GeneralBlock("survivors_block_181", Survivors.MODID + ":metal/" + "metal_52"));
        register(new GeneralBlock("survivors_block_182", Survivors.MODID + ":metal/" + "metal_53"));
        register(new GeneralBlock("survivors_block_183", Survivors.MODID + ":metal/" + "metal_54"));
        register(new GeneralBlock("survivors_block_184", Survivors.MODID + ":metal/" + "metal_55"));
        register(new GeneralBlock("survivors_block_185", Survivors.MODID + ":metal/" + "metal_56"));
        register(new GeneralBlock("survivors_block_186", Survivors.MODID + ":metal/" + "metal_57"));
        register(new GeneralBlock("survivors_block_187", Survivors.MODID + ":metal/" + "metal_58"));
        register(new GeneralBlock("survivors_block_188", Survivors.MODID + ":metal/" + "metal_59"));
        register(new GeneralTransparentBlock("survivors_block_189", Survivors.MODID + ":metal/" + "metal_60"));
        register(new GeneralBlock("survivors_block_190", Survivors.MODID + ":khaki/" + "khaki_1"));
        register(new GeneralBlock("survivors_block_191", Survivors.MODID + ":khaki/" + "khaki_2"));
        register(new GeneralBlock("survivors_block_192", Survivors.MODID + ":khaki/" + "khaki_3"));
        register(new GeneralTransparentBlock("survivors_block_193", Survivors.MODID + ":khaki/" + "khaki_4"));
        register(new GeneralTransparentBlock("survivors_block_194", Survivors.MODID + ":khaki/" + "khaki_5"));
        register(new GeneralTransparentBlock("survivors_block_195", Survivors.MODID + ":khaki/" + "khaki_6"));
        register(new GeneralBlock("survivors_block_196", Survivors.MODID + ":metal/" + "metal_61"));
        register(new GeneralBlock("survivors_block_197", Survivors.MODID + ":metal/" + "metal_62"));
        register(new GeneralTransparentBlock("survivors_block_198", Survivors.MODID + ":glass/" + "glass_1"));
        register(new GeneralTransparentBlock("survivors_block_199", Survivors.MODID + ":glass/" + "glass_2"));
        register(new GeneralTransparentBlock("survivors_block_200", Survivors.MODID + ":glass/" + "glass_3"));
        register(new GeneralTransparentBlock("survivors_block_201", Survivors.MODID + ":glass/" + "glass_4"));
        register(new GeneralTransparentBlock("survivors_block_202", Survivors.MODID + ":glass/" + "glass_5"));
        register(new GeneralTransparentBlock("survivors_block_203", Survivors.MODID + ":glass/" + "glass_6"));
        register(new GeneralTransparentBlock("survivors_block_204", Survivors.MODID + ":glass/" + "glass_7"));
        register(new PaneBlock("survivors_block_205", Survivors.MODID + ':' + "glass/glass_1", Survivors.MODID + ':' + "glass/glass_pane_1_top"));
        register(new PaneBlock("survivors_block_206", Survivors.MODID + ':' + "glass/glass_2", Survivors.MODID + ':' + "glass/glass_pane_2_top"));
        register(new PaneBlock("survivors_block_207", Survivors.MODID + ':' + "glass/glass_3", Survivors.MODID + ':' + "glass/glass_pane_1_top"));
        register(new PaneBlock("survivors_block_208", Survivors.MODID + ':' + "glass/glass_4", Survivors.MODID + ':' + "glass/glass_pane_2_top"));
        register(new PaneBlock("survivors_block_209", Survivors.MODID + ':' + "glass/glass_5", Survivors.MODID + ':' + "glass/glass_pane_2_top"));
        register(new PaneBlock("survivors_block_210", Survivors.MODID + ':' + "glass/glass_6", Survivors.MODID + ':' + "glass/glass_pane_2_top"));
        register(new PaneBlock("survivors_block_211", Survivors.MODID + ':' + "glass/glass_7", Survivors.MODID + ':' + "glass/glass_pane_2_top"));
        register(new GeneralTransparentBlock("survivors_block_212", Survivors.MODID + ":khaki/" + "khaki_7"));
    }

}
